function get(id: string): HTMLElement {
  const el = document.getElementById(id);
  if (!el) throw new Error(`Missing DOM element: #${id}`);
  return el;
}

export const el = {
  app:             get("app"),
  sidebar:         get("sidebar"),
  sidebarCollapse: get("sidebarCollapse"),
  sidebarShowBtn:  get("sidebarShowBtn"),
  connList:        get("connList"),
  newConnBtn:      get("newConnBtn"),
  schemaTree:      get("schemaTree"),
  schemaSearch:    get("schemaSearch") as HTMLInputElement,
  reloadSchema:    get("reloadSchema"),
  tabsTrack:       get("tabsTrack"),
  addTabBtn:       get("addTabBtn"),
  connPillDot:     get("connPillDot"),
  connPillName:    get("connPillName"),
  connPillChange:  get("connPillChange"),
  toolbarDbLabel:  get("toolbarDbLabel"),
  queryToolbar:    get("queryToolbar") as HTMLElement | null,
  explainBtn:      get("explainBtn"),
  runBtn:          get("runBtn"),
  editor:          get("editor") as HTMLTextAreaElement,
  gutter:          get("gutter"),
  hlLayer:         get("hlLayer"),
  divider:         get("divider"),
  editorPanel:     get("editorPanel"),
  resultsPanel:    get("resultsPanel"),
  tableEditorPanel: get("tableEditorPanel"),
  erdPanel:        get("erdPanel"),
  workspace:       get("workspace"),
  resultsBody:     get("resultsBody"),
  resultsEmpty:    get("resultsEmpty"),
  resultsCount:    get("resultsCount"),
  resultsTime:     get("resultsTime"),
  copyJsonBtn:     get("copyJsonBtn"),
  exportCsvBtn:    get("exportCsvBtn"),
  statusIndicator: get("statusIndicator"),
  statusText:      get("statusText"),
  newSchemaBtn:    get("newSchemaBtn"),
  newTableBtn:     get("newTableBtn"),
  ctxMenu:         get("ctxMenu"),
  ctxNewTable:     get("ctxNewTable"),
  ctxOpenErd:      get("ctxOpenErd"),
  ctxDropSchema:   get("ctxDropSchema"),
  ctxEditTable:    get("ctxEditTable"),
  ctxDropTable:    get("ctxDropTable"),
  ctxTruncate:     get("ctxTruncate"),
  ctxMaintSep:     get("ctxMaintSep"),
  ctxVacuum:       get("ctxVacuum"),
  ctxReindex:      get("ctxReindex"),
  qhistPanel:      get("qhistPanel"),
  qhistList:       get("qhistList"),
  qhistClear:      get("qhistClear"),
  qhistClose:      get("qhistClose"),
  historyBtn:      get("historyBtn"),
  formatBtn:       get("formatBtn"),
  ddlModal:        get("ddlModal"),
  ddlModalTitle:   get("ddlModalTitle"),
  ddlModalClose:   get("ddlModalClose"),
  ddlFormArea:     get("ddlFormArea"),
  ddlCancelBtn:    get("ddlCancelBtn"),
  ddlGenerateBtn:  get("ddlGenerateBtn") as HTMLButtonElement,
  themeBtn:        get("themeBtn"),
  installBtn:      get("installBtn"),
  connModal:       get("connModal"),
  connModalClose:  get("connModalClose"),
  connTestBtn:     get("connTestBtn") as HTMLButtonElement,
  connSaveBtn:     get("connSaveBtn"),
  connDeleteBtn:   get("connDeleteBtn"),
  connTestResult:  get("connTestResult"),
  connTestIcon:    get("connTestIcon"),
  connTestMsg:     get("connTestMsg"),
  connTestTime:    get("connTestTime"),
  modalSavedList:  get("modalSavedList"),
  mConnName:       get("mConnName") as HTMLInputElement,
  mDbType:         get("mDbType") as HTMLSelectElement,
  mHost:           get("mHost") as HTMLInputElement,
  mHostLabel:      get("mHostLabel"),
  mPort:           get("mPort") as HTMLInputElement,
  mPortField:      get("mPortField"),
  mUser:           get("mUser") as HTMLInputElement,
  mPass:           get("mPass") as HTMLInputElement,
  mCredFields:     get("mCredFields"),
  mDatabase:       get("mDatabase") as HTMLInputElement,
  mSsl:            get("mSsl") as HTMLInputElement,
  themeColorMeta:  get("themeColorMeta") as HTMLMetaElement,
  acDropdown:      get("acDropdown"),
  lockBtn:         get("lockBtn"),
  lockScreen:      get("lockScreen"),
  lockPinInput:    get("lockPinInput") as HTMLInputElement,
  lockUnlockBtn:   get("lockUnlockBtn") as HTMLButtonElement,
  lockError:       get("lockError"),
  lockSub:         get("lockSub"),
  lockSetupHint:   get("lockSetupHint"),
  lockSetPinBtn:   get("lockSetPinBtn"),
  setPinModal:     get("setPinModal"),
  setPinClose:     get("setPinClose"),
  setPinCancelBtn: get("setPinCancelBtn"),
  setPinSaveBtn:   get("setPinSaveBtn"),
  clearPinBtn:     get("clearPinBtn"),
  newPinInput:     get("newPinInput") as HTMLInputElement,
  confirmPinInput: get("confirmPinInput") as HTMLInputElement,
  setPinError:     get("setPinError"),
  // AI chat panel
  aiBtn:           get("aiBtn"),
  chatPanel:       get("chatPanel"),
  chatClose:       get("chatClose"),
  chatMessages:    get("chatMessages"),
  chatInput:       get("chatInput") as HTMLTextAreaElement,
  chatSendBtn:     get("chatSendBtn"),
  chatFt:          get("chatFt"),
  // Settings panel
  settingsBtn:     get("settingsBtn"),
  settingsPanel:   get("settingsPanel"),
  settingsClose:   get("settingsClose"),
  sAiEnabled:      get("sAiEnabled") as HTMLInputElement,
  sAiProvider:     get("sAiProvider") as HTMLSelectElement,
  sAiKey:          get("sAiKey") as HTMLInputElement,
  sAiModel:        get("sAiModel") as HTMLInputElement,
  sAiBaseUrl:      get("sAiBaseUrl") as HTMLInputElement,
  sAiMaxTokens:    get("sAiMaxTokens") as HTMLInputElement,
  sAiSave:         get("sAiSave"),
  sAiSaveStatus:   get("sAiSaveStatus"),
  sAiKeyField:     get("sAiKeyField"),
  sAiBaseUrlField: get("sAiBaseUrlField"),
  // Server power menu
  serverPowerBtn:  get("serverPowerBtn") as HTMLButtonElement,
  serverPopover:   get("serverPopover"),
  serverDot:       get("serverDot"),
  popRestartBtn:   get("popRestartBtn") as HTMLButtonElement,
  popStopBtn:      get("popStopBtn") as HTMLButtonElement,
  serverPopStatus: get("serverPopStatus"),
};
